// packages/renderer/src/components/UploadFiles.tsx
import {Button, Space, Upload} from 'antd';
import type {UploadChangeParam} from 'antd/es/upload';
import {useState} from 'react';
import {produce} from 'immer';
import {CloseOutlined, FileDoneOutlined, PlusOutlined} from '@ant-design/icons';
import styled from '@emotion/styled';

export default function UploadFiles({onChange}:{onChange: (files: Record<string, string>) => void}) {
  const [fileNames, setFileNames] = useState<Record<string, string>>({
    outboundInvoices: '',
    inboundInvoices: '',
    calculate: '',
  });
  const [filePaths, setFilePaths] = useState<Record<string, string>>({});

  function addFile(file: {path: string; type: string}) {
    filePaths[file.type] = file.path;
    setFilePaths({...filePaths});
    onChange({...filePaths});
  }

  function handleRemoveClick(type: string) {
    delete filePaths[type];
    setFilePaths({...filePaths});
    setFileNames(
      produce(draft => {
        draft[type] = '';
      }),
    );
    onChange({...filePaths});
  }

  const handleChange = (info: UploadChangeParam, type: string) => {
    setFileNames(
      produce(draft => {
        draft[type] = info.file.originFileObj?.name || '';
      }),
    );
    if (info.file.originFileObj?.name) {
      addFile({
        path: info.file.originFileObj!.path,
        type,
      });
    }
  };

  return (
    <Space>
      <Space direction="vertical">
        出库发票
        <StyledUpdload
          name="avatar"
          listType="picture-card"
          showUploadList={false}
          accept=".xlsx"
          customRequest={()=>{}}
          onChange={(e: UploadChangeParam) => handleChange(e, 'outboundInvoices')}
        >
          <Space
            direction="vertical"
            style={{
              fontSize: '12px',
              padding: '10px',
            }}
          >
            {fileNames.outboundInvoices ? (
              <FileDoneOutlined style={{fontSize: '30px', color: 'green'}}></FileDoneOutlined>
            ) : (
              <PlusOutlined style={{fontSize: '30px', color: 'gray'}}></PlusOutlined>
            )}
            {fileNames.outboundInvoices}
          </Space>
          {fileNames.outboundInvoices ? (
            <Button
              type="text"
              size="small"
              style={{position: 'absolute', right: '0', top: '0'}}
              onClick={e => {
                e.stopPropagation();
                handleRemoveClick('outboundInvoices');
              }}
            >
              <CloseOutlined style={{color: 'gray'}} />
            </Button>
          ) : null}
        </StyledUpdload>
      </Space>
      <Space direction="vertical">
        测算表
        <StyledUpdload
          name="avatar"
          listType="picture-card"
          showUploadList={false}
          customRequest={()=>{}}
          accept=".xlsx"
          onChange={(e: UploadChangeParam) => handleChange(e, 'calculate')}
        >
          <Space
            direction="vertical"
            style={{
              fontSize: '12px',
              padding: '10px',
            }}
          >
            {fileNames.calculate ? (
              <FileDoneOutlined style={{fontSize: '30px', color: 'green'}}></FileDoneOutlined>
            ) : (
              <PlusOutlined style={{fontSize: '30px', color: 'gray'}}></PlusOutlined>
            )}
            {fileNames.calculate}
          </Space>
          {fileNames.calculate ? (
            <Button
              type="text"
              size="small"
              style={{position: 'absolute', right: '0', top: '0'}}
              onClick={e => {
                e.stopPropagation();
                handleRemoveClick('calculate');
              }}
            >
              <CloseOutlined style={{color: 'gray'}} />
            </Button>
          ) : null}
        </StyledUpdload>
      </Space>
      <Space direction="vertical">
        购进发票
        <StyledUpdload
          name="avatar"
          listType="picture-card"
          showUploadList={false}
          customRequest={()=>{}}
          accept=".xlsx"
          onChange={(e: UploadChangeParam) => {
            handleChange(e, 'inboundInvoices');
          }}
        >
          <Space
            direction="vertical"
            style={{
              fontSize: '12px',
              padding: '10px',
            }}
          >
            {fileNames.inboundInvoices ? (
              <FileDoneOutlined style={{fontSize: '30px', color: 'green'}}></FileDoneOutlined>
            ) : (
              <PlusOutlined style={{fontSize: '30px', color: 'gray'}}></PlusOutlined>
            )}
            {fileNames.inboundInvoices}
          </Space>
          {fileNames.inboundInvoices ? (
            <Button
              type="text"
              size="small"
              style={{position: 'absolute', right: '0', top: '0'}}
              onClick={e => {
                e.stopPropagation();
                handleRemoveClick('inboundInvoices');
              }}
            >
              <CloseOutlined style={{color: 'gray'}} />
            </Button>
          ) : null}
        </StyledUpdload>
      </Space>
    </Space>
  );
}

const StyledUpdload = styled(Upload)`
  position: relative;
  button {
    display: none;
  }
  &:hover {
    button {
      display: block;
    }
  }
`;

// packages/renderer/src/components/UploadFiles.vue
<template>
  <a-space>
    <a-space direction="vertical">
      出库发票
      <a-upload
        name="avatar"
        list-type="picture-card"
        class="file-uploader"
        :show-upload-list="false"
        action="https://www.mocky.io/v2/5cc8019d300000980a055e76"
        accept=".xlsx"
        @change="(e: UploadChangeParam) => handleChange(e, 'outboundInvoices')"
      >
        <a-space
          direction="vertical"
          :style="{
            fontSize: '12px',
            padding: '10px',
          }"
        >
          <template v-if="uploadFlag.outboundInvoices">
            <FileDoneOutlined :style="{fontSize: '30px', color: 'green'}"></FileDoneOutlined>
            {{ uploadFlag.outboundInvoices }}
          </template>
          <template v-else>
            <plus-outlined :style="{fontSize: '30px', color: 'gray'}"></plus-outlined>
          </template>
        </a-space>
        <a-button
          v-if="uploadFlag.outboundInvoices"
          type="text"
          size="small"
          style="position: absolute; right: 10px; top: 4px"
          @click.stop="handleRemoveClick('outboundInvoices')"
        >
          <template #icon>
            <CloseOutlined style="color: gray" />
          </template>
        </a-button>
      </a-upload>
    </a-space>
    <a-space direction="vertical">
      测算表
      <a-upload
        name="avatar"
        list-type="picture-card"
        class="file-uploader"
        :show-upload-list="false"
        action="https://www.mocky.io/v2/5cc8019d300000980a055e76"
        accept=".xlsx"
        @change="(e: UploadChangeParam) => handleChange(e, 'calculate')"
      >
        <a-space
          direction="vertical"
          :style="{
            fontSize: '12px',
            padding: '10px',
          }"
        >
          <template v-if="uploadFlag.calculate">
            <FileDoneOutlined :style="{fontSize: '30px', color: 'green'}"></FileDoneOutlined>
            {{ uploadFlag.calculate }}
          </template>
          <template v-else>
            <plus-outlined :style="{fontSize: '30px', color: 'gray'}"></plus-outlined>
          </template>
        </a-space>
        <a-button
          v-if="uploadFlag.calculate"
          type="text"
          size="small"
          style="position: absolute; right: 10px; top: 4px"
          @click.stop="handleRemoveClick('calculate')"
        >
          <template #icon>
            <CloseOutlined style="color: gray" />
          </template>
        </a-button>
      </a-upload>
    </a-space>
    <a-space direction="vertical">
      购进发票
      <a-upload
        name="avatar"
        list-type="picture-card"
        class="file-uploader"
        :show-upload-list="false"
        action="https://www.mocky.io/v2/5cc8019d300000980a055e76"
        accept=".xlsx"
        @change="(e: UploadChangeParam) => handleChange(e, 'inboundInvoices')"
      >
        <a-space
          direction="vertical"
          :style="{
            fontSize: '12px',
            padding: '10px',
          }"
        >
          <template v-if="uploadFlag.inboundInvoices">
            <FileDoneOutlined :style="{fontSize: '30px', color: 'green'}"></FileDoneOutlined>
            {{ uploadFlag.inboundInvoices }}
          </template>
          <template v-else>
            <plus-outlined :style="{fontSize: '30px', color: 'gray'}"></plus-outlined>
          </template>
        </a-space>
        <a-button
          v-if="uploadFlag.inboundInvoices"
          type="text"
          size="small"
          style="position: absolute; right: 10px; top: 4px"
          @click.stop="handleRemoveClick('inboundInvoices')"
        >
          <template #icon>
            <CloseOutlined style="color: gray" />
          </template>
        </a-button>
      </a-upload>
    </a-space>
  </a-space>
</template>
<script lang="ts" setup>
import {ref, defineEmits} from 'vue';
import {PlusOutlined, FileDoneOutlined, CloseOutlined} from '@ant-design/icons-vue';
import type {UploadChangeParam} from 'ant-design-vue';
const emit = defineEmits(['change']);
const files: Record<string, string> = {};
const uploadFlag = ref<Record<string, string>>({
  outboundInvoices: '',
  inboundInvoices: '',
  calculate: '',
});

const handleChange = (info: UploadChangeParam, type: string) => {
  uploadFlag.value[type] = info.file.originFileObj?.name || '';
  if (uploadFlag.value[type]) {
    addFile({
      path: info.file.originFileObj!.path,
      type,
    });
  }
};

function handleRemoveClick(type: string) {
  delete files[type];
  uploadFlag.value[type] = '';
  emit('change', files);
}

function addFile(file: {path: string; type: string}) {
  if (files[file.type]) {
    files[file.type] = file.path;
  } else {
    files[file.type] = file.path;
  }
  emit('change', files);
}
</script>
<style scoped>
.file-uploader {
  position: relative;
  button {
    display: none;
  }
  &:hover {
    button {
      display: block;
    }
  }
}
</style>
